[project]
name = "sou"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fotis", email = "fotiskapotos@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "click>=8.4.2",
    "pytest>=9.1.1",
]

[project.scripts]
sou = "sou:main"

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[tool.ruff]
format.preview = true